name: unit-testing

on:
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test BiBi.IO
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: BiBi.IO.Tests
          report_name: IO Tests
          report_title: IO Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: BiBi.IO.Tests.md
          gist_badge_label: 'BiBi.IO: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
      - name: Test BiBi.Memory
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: BiBi.Memory.Tests
          report_name: Memory Tests
          report_title: Memory Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: BiBi.Memory.Tests.md
          gist_badge_label: 'BiBi.Memory: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
